Repository jenkinsci/ibmi-steps-plugin, pull requests merged in 2025-03, with the labels that each got.

#2 Setting up project for CD
  .github/dependabot.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: developer

#3 Update LoggerWrapper.java
  src/main/java/org/jenkinsci/plugins/ibmisteps/model/LoggerWrapper.java
Labels: java

#4 Fixed documentation's TOC and indentation
  README.md
Labels: chore

#5 Migrate tests to JUnit5
  src/main/java/org/jenkinsci/plugins/ibmisteps/configuration/IBMiServerConfiguration.java
  src/test/java/org/jenkinsci/plugins/ibmisteps/configuration/IBMiGlobalConfigurationTests.java
  src/test/java/org/jenkinsci/plugins/ibmisteps/configuration/IBMiServerConfigurationTests.java
Labels: developer, tests, java

#7 Fixed command example in documentation
  README.md
Labels: documentation

#6 Bump jt400 + fix NPE in ibmiCommand
  README.md
  pom.xml
  src/main/java/org/jenkinsci/plugins/ibmisteps/model/CallResult.java
  src/main/java/org/jenkinsci/plugins/ibmisteps/steps/IBMiCommandStep.java
  src/main/resources/org/jenkinsci/plugins/ibmisteps/Messages.properties
Labels: bug, dependencies

#8 Fixed ibmiCommand failOnError default value
  src/main/java/org/jenkinsci/plugins/ibmisteps/steps/IBMiCommandStep.java
Labels: bug
